title: <p align="center"> Emre Demir </p>

logo: "/images/whiteFoto.jpeg?raw=true"

description: <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/emred/">LinkedIn</a> |
  <a href="https://github.com/emreds/">GitHub</a>
  </p>

  <p align="justify">
  I am pursing MS degree in Computer Science at Technical University of Munich.
  <br><br>
  I am currently writing my thesis on Hardware Aware Neural Architecture Search at German Aerospace Agency(DLR).
  In the meantime I work as a part-time Data Scientist at Siemens Financial Services.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: G-DN3H87HFK1 # Google Analytics tracking ID
