title: <p align="center"> Emre Demir </p>

logo: "/images/whiteFoto.jpeg?raw=true"

description: <p align="left">
  <a href="https://www.linkedin.com/in/emred/">LinkedIn</a> |
  <a href="https://github.com/emreds/">GitHub</a>
  </p>

  <p align="justify">
  I hold a Master's Degree in Computer Science from the Technical University of Munich. 
  My master's thesis, completed in collaboration with the German Aerospace Center (DLR), 
  focused on optimizing neural network designs for enhanced hardware compatibility.
  I possess a Bachelor's Degree in Computer Engineering.
  <br><br>
  
  Currently, I am employed as a Machine Learning Engineer at Certivity, 
  where I specialize in addressing regulatory challenges through the application of 
  Natural Language Processing (NLP) and advanced software solutions.
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: G-DN3H87HFK1 # Google Analytics tracking ID
